# bitore.sig
$GIT: .IT.3.GUT/maki
IRWM_ID.DB.DATABASE: BITORE_34173.1337_118331
Step 1: Clone the repository or update your local repository with the latest changes.
git pull origin main
Step 2: Switch to the head branch of the pull request.
git checkout Master
Step 3: Merge the base branch into the head branch.
git merge main
Step 4: Fix the conflicts and commit the result.
See Resolving a merge conflict using the command line for step-by-step instructions on resolving merge conflicts.
Step 5: Push the changes.
git push -u origin Master
https://github.com/mowjoejoejoejoe/docs/compare/main...0-wiz-0:docs:TingluoHuang-patch-1
BEGIN :run::/Runs::/'Run ''
'Runs::/Action::/:Build::/scripts::/Run-on :Runs: required
os: osx
install:
  - brew update
  - brew install python || true
  - brew install brew-cask || true
  - brew cask install google-chrome || true
  - brew cask install chromedriver || true
  - brew install flex bison || true
  - pip install selenium pysocks urllib3 requests pyperclip
script:
  - make -C dsl/
  - python src/automate.py
