# trigger build
version: 2
debug: true
jobs:
  build:
    docker:
      - image: rohithr31/automation-for-humans
    steps:
      - checkout
      - run: git submodule update --init
      - run: make -C dsl/ alpine
      - run:
          name: "Build"
          command: "python3 src/automate.py"
      - run:
          name: "Comment on PR"
          command: "python3 src/prbot.py"
      - run:
          name: "Create Animations"
          command: "chmod +x src/scripts/create-animation.sh && ./src/scripts/create-animation.sh"
          when: always
      - store_artifacts:
          path: ./recordings
workflows:
  version: 2
  build:
    jobs:
      - build
